### ISSUE TITLE
[Bounty] lastblock can't see  even  mouse hover

### ISSUE THREAD

**Issue by zhongshuo** [tronprotocol/wallet-web#168]
![default](https://user-images.githubusercontent.com/525405/39684161-675302de-51ec-11e8-9bcb-68d905420e50.PNG)

**Comment by Jacob8765** [comment]
I'm not sure exactly what you mean... Do you have the same problem as in #155?

**Comment by zhongshuo** [comment]
yes ,it's same problem ,sorry,I didn't notice #155 before
