### ISSUE TITLE
Logo overlaps menu

### ISSUE THREAD

**Issue by Rovak** [tronprotocol/wallet-web#5]
On some resolutions the logo overlaps the menu. The logo was given a `position: fixed` because else the menu would not align properly.

Look for a solution to keep the logo on the left without messing up the top menu.

## Example
![screenshot from 2018-04-02 23-22-14](https://user-images.githubusercontent.com/376155/38216995-e0fd814e-36cc-11e8-93df-c5a540686ac3.png)

**Comment by daiky00** [comment]
@everyone I made a pull request. Please let me know what you guys think about my approach?

https://github.com/tronprotocol/wallet-web/pull/11
